language: php

php:
  - 5.6

build_image: shippableimages/ubuntu1404_php

env:
  global:
    - PROJECT=monii-aggregate-event-storage
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - secure: JkxZmP7r1oKxx7lp+GBv3P1rWJT7hpq9zQ4pMnXkzbz+F6yxWZgt8MHcqQ125+eNUUmJ9XLqz3/G4O6Gye/WflEHY2NZo797wJeMvhVZzRYosURU1yD9Of07PZ6G56kh70vRX9Twd7N7SeVQ8In+MGh/b1M44UtgIxrPPAP2spb90N/vY/ynrM/4fh1Gp1wPoNwZg6CKT2fNHfFG7dkZCm8st1Fv6da6tK0pU6x0g/QMshA/5jYdkZ7srIbtS2R9ZQDR4pNd6dRNUW/Y1J9Scu80SqCyr9r9CbMzrhWMcptWvvj6yT97bX6gjuZiKCnC6E2XAJ44SYPqDp9oCxFLZg==
    - secure: mSKECDwG+CSwF5XEo1LZ/fbv7/c9C9B/UGc2iADmhFZwqp7FiG7x1PlxkDEBn9tLrYGRo4Y6G0B59yXorPFy1DC47nj7aZ3U3ApY24RA83m8OFQ5bRwUFFCYA8gukQ05gXWJSLPNMuzqVMni0hCpSOU4ph6Zkx676qECEV68eozeeuQecuOveq6XOX9jHzF/SX1qkFdxecj272n7uVwc2t1WV9xmw70gMh1izMOPIQQe+EzWLn0NJPE91OH1oW0GEnZk7gFWne/kgFv+kkT8zXb0yU4gJGWTcR5rHNcx8OckymnkkM6zd1WLGV0wgY0Xp2mZo2FwZVtDT5pJtKw++A==

branches:
  only:
    - master

before_install:
  - export PATH=$HOME/.phpenv/bin:$HOME/.phpenv/extensions:$PATH && eval "$(phpenv init -)"
  - phpenv global $SHIPPABLE_PHP_VERSION
  - php --version

before_script:
  - mkdir -p $CI_REPORTS
  - mkdir -p $COVERAGE_REPORTS
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --log-junit $CI_REPORTS/junit.xml --coverage-xml $COVERAGE_REPORTS --coverage-clover=$COVERAGE_REPORTS/coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_TOKEN" --format=php-clover $COVERAGE_REPORTS/coverage.clover

after_failure:
  - python support/shippable/slack_notifier.py --project $PROJECT --token $SLACK_TOKEN --coverage-clover=$COVERAGE_REPORTS/coverage.clover

after_success:
  - python support/shippable/slack_notifier.py --project $PROJECT --token $SLACK_TOKEN --coverage-clover=$COVERAGE_REPORTS/coverage.clover -s

notifications:
   email: false

cache: true
